servidor:
 cantidadCli: '1'

users:
 - name: 'user1'
   password: 'pass1'
 - name: 'user2'
   password: 'pass2'
 - name: 'user3'
   password: 'pass3'
 - name: 'user4'
   password: 'pass4'
 - name: 'user5'
   password: 'pass5'


conexion:
 ip: '192.168.10.20'
 puerto: '8080'
